apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: atom
  labels:
    app: atom
spec:
  selector:
    matchLabels:
      app: atom
  replicas: 1
  template:
    metadata:
      labels:
        app: atom
    spec:
      terminationGracePeriodSeconds: 900
      securityContext:
        fsGroup: 1000
      containers:
      - image: boomi/atom:release
        imagePullPolicy: Always
        name: atom-node
        ports:
        - containerPort: 9090
          protocol: TCP
        resources:
          limits:
            cpu: "1000m"
            memory: "1024Mi"
          requests:
            cpu: "500m"
            memory: "768Mi"
        readinessProbe:
          periodSeconds: 10
          initialDelaySeconds: 10
          httpGet:
            path: /_admin/readiness
            port: 9090
        livenessProbe:
          periodSeconds: 60
          httpGet:
            path: /_admin/liveness
            port: 9090
        env:
        - name: BOOMI_ATOMNAME
          value: "minik-boomi-atom"
        - name: ATOM_LOCALHOSTID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: INSTALL_TOKEN
          value: "atom-5b2d3b95-7a8f-4684-928c-692c940b4dc4"
        - name : BOOMI_ENVIRONMENTID
          value: "40590140-dc5b-4c49-89f9-47f99641a0d4"
